# Generated by Django 3.1 on 2021-12-21 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211221_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='quentity',
            field=models.IntegerField(default=1, verbose_name='Кол-во статей'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.category', verbose_name='Категория'),
        ),
    ]
