# Generated by Django 3.1 on 2022-02-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220204_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='views_posts',
            field=models.IntegerField(default=0),
        ),
    ]
